# Generated by Django 5.1.6 on 2025-02-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variationmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
